# golangci-lint configuration for unified-thinking server
# Documentation: https://golangci-lint.run/usage/configuration/
# Compatible with golangci-lint v2.6.2+

version: "2"

run:
  timeout: 5m
  tests: true
  build-tags: []

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter (includes gosimple in v2.x)
    - unused        # Check for unused constants, variables, functions

  exclusions:
    rules:
      # Disable errcheck entirely for test files (cleanup operations not critical)
      - path: '_test\.go$'
        linters:
          - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
