# golangci-lint configuration for unified-thinking server
# Documentation: https://golangci-lint.run/usage/configuration/
# Minimal configuration compatible with golangci-lint v2.x schema (v2.5.0+)
version: "2"

run:
  timeout: 5m
  tests: true
  build-tags: []

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused constants, variables, functions
    - gofmt         # Check formatting
    - misspell      # Check for misspelled words

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
