# golangci-lint configuration for unified-thinking server
# Documentation: https://golangci-lint.run/usage/configuration/
# Minimal configuration compatible with golangci-lint v2.x schema (v2.5.0+)
version: "2"

run:
  timeout: 5m
  tests: true
  build-tags: []

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused constants, variables, functions
    - misspell      # Check for misspelled words
    - goconst       # Check for repeated strings
    - gosec         # Security-focused linter

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude common test patterns from errcheck
  exclude-rules:
    # Test cleanup: defer Close() calls
    - path: _test\.go
      text: "Error return value of.*Close.*is not checked"
      linters:
        - errcheck

    # Test environment: os.Setenv/Unsetenv
    - path: _test\.go
      text: "Error return value of `os\\.(Setenv|Unsetenv)`"
      linters:
        - errcheck

    # Test storage operations (non-critical errors in test setup)
    - path: _test\.go
      text: "Error return value of `(store|storage|tracker)\\."
      linters:
        - errcheck

    # Test handlers (non-critical errors in test execution)
    - path: _test\.go
      text: "Error return value of `(handler|server)\\."
      linters:
        - errcheck

    # Test helper functions
    - path: _test\.go
      text: "Error return value of `(sr|tx)\\."
      linters:
        - errcheck
